/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.NguoiData;
import controller.QuanLyData;
import controller.SQLPhongTro;
import java.awt.HeadlessException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.event.DocumentListener;
import model.Nguoi;
import model.QuanLy;
import net.proteanit.sql.DbUtils;
import static view.UpdateTable.ps;
import static view.frmKhachHang.sqlDg;


/**
 *
 * @author DELL
 */
public class frmQuanLy extends javax.swing.JFrame {
    public static Connection con = SQLPhongTro.getSQLPhongTro();
    QuanLyData khdata= new QuanLyData();
    public static PreparedStatement ps = null;
    public static String sql = "SELECT * FROM tblQuanLy order by KhachHang asc";
    public JTextArea getTa() {
        return In;
    }
    public JButton inbc() {
        return btnIn;
    }

    /**
     * Creates new form frmQuanLy
     */
    public frmQuanLy() {

        initComponents();
        setLocationRelativeTo(null);
        
        UpdateTable.LoadData(sql, tblQuanLy);
        try{
            String sql1 = "SELECT COUNT(ID) as khachhang FROM tblKhachHang";
            String sql2 = "SELECT COUNT(MaPhong) as thuephong FROM tblThuePhong";
            String sql3 = "SELECT SUM(TongTien) as tongtien FROM tblDichVu";
            String sql4 = "SELECT SUM(ThanhTien) as thanhtien FROM tblThongKe";
            ResultSet rs1 = UpdateTable.ShowTextField(sql1);
            ResultSet rs2 = UpdateTable.ShowTextField(sql2);
            ResultSet rs3 = UpdateTable.ShowTextField(sql3);
            ResultSet rs4 = UpdateTable.ShowTextField(sql4);
            if(rs1.next()) this.lbTongKhach.setText("            Tổng số khách hàng: "+Integer.toString(rs1.getInt("khachhang"))+" "+"khách hàng.");
            if(rs2.next()) this.lbTongPhong.setText("            Tổng số phòng thuê: " + Integer.toString(rs2.getInt("thuephong"))+" "+"phòng.");
            if(rs3.next()) this.lbTongDV.setText("            Tổng số tiền dịch vụ: "+Integer.toString(rs3.getInt("tongtien"))+" "+"VNĐ");
            if(rs4.next()) this.lbQuaHan.setText("            Tổng doanh thu: "+Integer.toString(rs4.getInt("thanhtien"))+" "+"VNĐ");
            
        }catch(SQLException e) {
            
        }
        ResultSet rs = null ;
        try {
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
        } catch (SQLException ex) {
            Logger.getLogger(frmQuanLy.class.getName()).log(Level.SEVERE, null, ex);
        }
        List l;
        l=DbUtils.resultSetToNestedList(rs);
        
        this.In.append(this.lbTongKhach.getText()+"\n");
        this.In.append(this.lbTongPhong.getText()+"\n");
        this.In.append(this.lbTongDV.getText()+"\n\n");
        
        this.In.append("-------------------------Thông Tin Chung--------------------\n\n");
        this.In.append("|Tên Khách Hàng|Phòng|Dịch Vụ|Ngày Thuê|Tiền cọc|Tình Trạng|\n");
        this.In.append("\n");
        
        for (int i = 0; i < l.size(); i++) {
        this.In.append(l.get(i).toString() + "\n");
        }
        this.In.append("\n");
        this.In.append(this.lbQuaHan.getText()+"\n\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        In = new javax.swing.JTextArea();
        btnIn = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPhongTro = new javax.swing.JTextField();
        txtKhachHang = new javax.swing.JTextField();
        txtDichVu = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblQuanLy = new javax.swing.JTable();
        lbTongKhach = new javax.swing.JLabel();
        lbTongPhong = new javax.swing.JLabel();
        lbTongDV = new javax.swing.JLabel();
        lbQuaHan = new javax.swing.JLabel();
        btnSua = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNgayThue = new javax.swing.JTextField();
        txtTienCoc = new javax.swing.JTextField();
        txtTinhTrang = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/one piece/quản lý_1.png"))); // NOI18N
        jLabel1.setText("Quản Lý Chung");

        In.setColumns(20);
        In.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        In.setRows(5);
        In.setText("\n");
        jScrollPane1.setViewportView(In);

        btnIn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/one piece/print.png"))); // NOI18N
        btnIn.setText("In Báo Cáo");
        btnIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInActionPerformed(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/one piece/exit.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Phòng trọ:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Khách hàng:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Dịch vụ:");

        tblQuanLy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblQuanLy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQuanLyMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblQuanLy);

        lbTongKhach.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbTongKhach.setForeground(new java.awt.Color(255, 0, 0));
        lbTongKhach.setText("?");

        lbTongPhong.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbTongPhong.setForeground(new java.awt.Color(255, 0, 0));
        lbTongPhong.setText("?");

        lbTongDV.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lbTongDV.setForeground(new java.awt.Color(255, 0, 0));
        lbTongDV.setText("?");

        lbQuaHan.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lbQuaHan.setForeground(new java.awt.Color(255, 0, 0));
        lbQuaHan.setText("?");

        btnSua.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/one piece/sửa.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/one piece/thêm.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/one piece/xoá.png"))); // NOI18N
        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Ngày thuê:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Tiền cọc:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Tình trạng:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4))
                                        .addGap(17, 17, 17)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtDichVu)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(txtPhongTro, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTienCoc, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNgayThue, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnThoat)
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnIn)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnThem)
                                    .addComponent(btnSua)
                                    .addComponent(btnXoa))
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbTongDV, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbTongPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbTongKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbQuaHan, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(254, 254, 254)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(25, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(btnIn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtNgayThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtTienCoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(txtPhongTro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSua)
                        .addGap(35, 35, 35)
                        .addComponent(btnXoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThoat))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTongKhach)
                        .addGap(33, 33, 33)
                        .addComponent(lbTongPhong)
                        .addGap(36, 36, 36)
                        .addComponent(lbTongDV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbQuaHan))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInActionPerformed

        try {
            JFileChooser jfc = new JFileChooser("Save File");
            if (jfc.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                String content = this.In.getText();
                jfc.setDialogTitle("Save File");
                try (FileOutputStream fos = new FileOutputStream(jfc.getSelectedFile())) {
                    fos.write(content.getBytes());
                    fos.flush();
                }
                JOptionPane.showMessageDialog(null, "Lưu thành công");
            }

        } catch (HeadlessException | IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnInActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed

       JOptionPane.showMessageDialog(this, "Quay lại trang chủ!");
       frmHome thoat = new frmHome();
       thoat.setVisible(true);
       dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void tblQuanLyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQuanLyMouseClicked

            try{
            int row = this.tblQuanLy.getSelectedRow();
            String IDrow = (this.tblQuanLy.getModel().getValueAt(row, 0)).toString();
            String sql = "SELECT * FROM tblQuanLy where KhachHang='"+IDrow+"'";
            ResultSet rs = UpdateTable.ShowTextField(sql);
            if(rs.next()) {
                this.txtKhachHang.setText(rs.getString("KhachHang"));
                this.txtPhongTro.setText(rs.getString("Phong"));
                this.txtDichVu.setText(rs.getString("DichVu"));
                this.txtNgayThue.setText(rs.getString("NgayThue"));
                this.txtTienCoc.setText(rs.getString("TienCoc"));
                this.txtTinhTrang.setText(rs.getString("TinhTrang"));
            }
        }catch(SQLException e) {
        }
    }//GEN-LAST:event_tblQuanLyMouseClicked

    public void resetForm(){
        txtKhachHang.setText("");
        txtPhongTro.setText("");
        txtDichVu.setText("");
        txtNgayThue.setText("");
        txtTienCoc.setText("");
        txtTinhTrang.setText("");
    }
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed

            if (this.txtKhachHang.getText().length()==0 ) JOptionPane.showMessageDialog(null, "Khách hàng không thể bỏ trống", "thông báo", 2);
            if (this.txtPhongTro.getText().length()==0 ) JOptionPane.showMessageDialog(null, "Phòng trọ không thể bỏ trống", "thông báo", 2);

            else {
                QuanLy d = new QuanLy(this.txtKhachHang.getText(), 
                    this.txtPhongTro.getText(),    
                    this.txtDichVu.getText(),
                    Date.valueOf(this.txtNgayThue.getText()),
                    Integer.parseInt(this.txtTienCoc.getText()),
                    this.txtTinhTrang.getText());
           try {
               QuanLyData.InsertQuanLy(d);
           } catch (SQLException ex) {
               Logger.getLogger(frmQuanLy.class.getName()).log(Level.SEVERE, null, ex);
           } 
        resetForm();
        UpdateTable.LoadData(sql, tblQuanLy);

        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed

        if (this.txtKhachHang.getText().length()==0) JOptionPane.showMessageDialog(null, "Khách hàng không thể bỏ trống", "thông báo", 2);
        if (this.txtPhongTro.getText().length()==0) JOptionPane.showMessageDialog(null, "Phòng trọ không thể bỏ trống", "thông báo", 2);
        else {
            QuanLy d = new QuanLy(this.txtKhachHang.getText(), 
                    this.txtPhongTro.getText(),    
                    this.txtDichVu.getText(),
                    Date.valueOf(this.txtNgayThue.getText()),
                    Integer.parseInt(this.txtTienCoc.getText()),
                    this.txtTinhTrang.getText());
                UpdateTable.LoadData(sql, tblQuanLy);
            try {
               QuanLyData.UpdateQuanLy(d);
               UpdateTable.LoadData(sql, tblQuanLy);
           } catch (SQLException ex) {
               Logger.getLogger(frmQuanLy.class.getName()).log(Level.SEVERE, null, ex);
               UpdateTable.LoadData(sql, tblQuanLy);
           }
        resetForm();
        UpdateTable.LoadData(sql, tblQuanLy);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed

        if (this.txtKhachHang.getText().length()==0) JOptionPane.showMessageDialog(null, "Khách hàng không thể bỏ chống", "thông báo", 2);
        else{
        if(khdata.XoaQuanLy(this.txtKhachHang.getText())) {
            JOptionPane.showMessageDialog(null, "Bạn đã xóa thành công", "Thông báo", 1);
            }
            else JOptionPane.showMessageDialog(null, "Có lỗi xảy ra", "Thông báo", 2);
            UpdateTable.LoadData(sql, tblQuanLy);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmQuanLy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea In;
    private javax.swing.JButton btnIn;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbQuaHan;
    private javax.swing.JLabel lbTongDV;
    private javax.swing.JLabel lbTongKhach;
    private javax.swing.JLabel lbTongPhong;
    private javax.swing.JTable tblQuanLy;
    private javax.swing.JTextField txtDichVu;
    private javax.swing.JTextField txtKhachHang;
    private javax.swing.JTextField txtNgayThue;
    private javax.swing.JTextField txtPhongTro;
    private javax.swing.JTextField txtTienCoc;
    private javax.swing.JTextField txtTinhTrang;
    // End of variables declaration//GEN-END:variables
}
